"use client";

import { useMemo, useState } from "react";

import { US_MAP_VIEWBOX, US_STATES } from "@/lib/usStatesGeometry";

/**
 * The by-state choropleth: real Census geometry (Albers USA composite,
 * generated by scripts/build_us_states_geometry.py) filled from the live DOL
 * disclosure aggregates.
 *
 * Interaction follows the house two-controls rule: the map is a browsing
 * surface, so hovering a state PREVIEWS it in the panel and clicking PINS it.
 * Keyboard: every state is focusable, focus previews, Enter/Space pins — no
 * hover-only path. The panel is in normal flow below the drawing, so nothing
 * is drawn over the map and nothing needs to reserve space.
 *
 * Fills are opaque color-mix tints of the brand lime over the card surface
 * (translucent fills over dark grounds burned us before), quantized into five
 * buckets by filing volume.
 */

export interface StateStat {
  state: string;
  total: number;
  certified: number;
  denied: number;
  withdrawn: number;
  medianDays: number | null;
  medianAnnualWage: number | null;
}

const BUCKET_MIX = [8, 16, 28, 44, 62] as const;

/** Too small to carry an inside label; they stack at the right edge. */
const SMALL_STATES = new Set(["VT", "NH", "MA", "RI", "CT", "NJ", "DE", "MD", "DC"]);

function fmtInt(n: number): string {
  return n.toLocaleString("en-US");
}

function fmtWage(n: number | null): string {
  return n == null ? "—" : `$${Math.round(n).toLocaleString("en-US")}`;
}

function certRate(s: StateStat): string {
  const decided = s.certified + s.denied;
  return decided === 0 ? "—" : `${((s.certified / decided) * 100).toFixed(1)}%`;
}

export function USStateMap({ states }: { states: StateStat[] }) {
  const [pinned, setPinned] = useState<string | null>(null);
  const [previewed, setPreviewed] = useState<string | null>(null);

  const byAbbr = useMemo(() => {
    const m = new Map<string, StateStat>();
    for (const s of states) m.set(s.state, s);
    return m;
  }, [states]);

  const thresholds = useMemo(() => {
    const totals = states.map((s) => s.total).sort((a, b) => a - b);
    if (totals.length === 0) return [];
    const q = (p: number) => totals[Math.min(totals.length - 1, Math.floor(p * totals.length))] ?? 0;
    return [q(0.2), q(0.4), q(0.6), q(0.8)];
  }, [states]);

  const bucketOf = (total: number): number => {
    let b = 0;
    for (const t of thresholds) if (total > t) b += 1;
    return Math.min(b, BUCKET_MIX.length - 1);
  };

  const activeAbbr = previewed ?? pinned;
  const active = activeAbbr ? byAbbr.get(activeAbbr) : undefined;
  const activeName = activeAbbr
    ? US_STATES.find((s) => s.abbr === activeAbbr)?.name ?? activeAbbr
    : null;

  const national = useMemo(() => {
    let total = 0;
    let certified = 0;
    let denied = 0;
    for (const s of states) {
      total += s.total;
      certified += s.certified;
      denied += s.denied;
    }
    return { total, certified, denied };
  }, [states]);

  return (
    <div>
      <div className="-mx-1 overflow-x-auto px-1">
        <svg
          viewBox={`0 0 ${US_MAP_VIEWBOX.w + 60} ${US_MAP_VIEWBOX.h}`}
          role="group"
          aria-label="PERM filings by worksite state"
          className="block h-auto w-full min-w-[560px]"
        >
          {US_STATES.map((shape) => {
            const stat = byAbbr.get(shape.abbr);
            const isActive = shape.abbr === activeAbbr || shape.abbr === pinned;
            const mix = stat ? BUCKET_MIX[bucketOf(stat.total)] : 0;
            return (
              <path
                key={shape.abbr}
                d={shape.d}
                role="button"
                tabIndex={0}
                aria-label={
                  stat
                    ? `${shape.name}: ${fmtInt(stat.total)} PERM filings`
                    : `${shape.name}: no data`
                }
                onMouseEnter={() => setPreviewed(shape.abbr)}
                onMouseLeave={() => setPreviewed(null)}
                onFocus={() => setPreviewed(shape.abbr)}
                onBlur={() => setPreviewed(null)}
                onClick={() => setPinned(shape.abbr)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    setPinned(shape.abbr);
                  }
                }}
                className="cursor-pointer outline-none focus-visible:stroke-[3]"
                style={{
                  fill: `color-mix(in srgb, var(--primary) ${mix}%, var(--card))`,
                  stroke: isActive ? "var(--foreground)" : "var(--border)",
                  strokeWidth: isActive ? 2.5 : 1,
                }}
              />
            );
          })}
          {/* State labels: big states carry theirs at the centroid with a
              halo (paint-order) so they read on every fill; the crowded
              Northeast nine move to a leader-line stack at the right edge,
              which is why the viewBox is wider than the geometry. Labels
              never intercept the pointer - the shapes own the interaction. */}
          <g aria-hidden="true" pointerEvents="none">
            {US_STATES.filter((sh) => !SMALL_STATES.has(sh.abbr)).map((sh) => (
              <text
                key={sh.abbr}
                x={sh.cx}
                y={sh.cy + 4}
                textAnchor="middle"
                fontSize="11"
                fontFamily="var(--font-mono)"
                fontWeight="700"
                fill="var(--foreground)"
                stroke="var(--card)"
                strokeWidth="3"
                paintOrder="stroke"
              >
                {sh.abbr}
              </text>
            ))}
            {US_STATES.filter((sh) => SMALL_STATES.has(sh.abbr))
              .sort((a, b) => a.cy - b.cy)
              .map((sh, i) => {
                const ly = 150 + i * 30;
                return (
                  <g key={sh.abbr}>
                    <line
                      x1={sh.cx}
                      y1={sh.cy}
                      x2={995}
                      y2={ly}
                      stroke="var(--foreground)"
                      strokeOpacity="0.35"
                      strokeWidth="1"
                    />
                    <text
                      x={1000}
                      y={ly + 4}
                      fontSize="11"
                      fontFamily="var(--font-mono)"
                      fontWeight="700"
                      fill="var(--foreground)"
                    >
                      {sh.abbr}
                    </text>
                  </g>
                );
              })}
          </g>

          {/* Re-draw the active outline last so it wins the paint order. */}
          {activeAbbr
            ? (() => {
                const shape = US_STATES.find((s) => s.abbr === activeAbbr);
                if (!shape) return null;
                return (
                  <path
                    d={shape.d}
                    fill="none"
                    stroke="var(--foreground)"
                    strokeWidth={2.5}
                    pointerEvents="none"
                  />
                );
              })()
            : null}
        </svg>
      </div>

      {/* Legend: five volume buckets, lowest to highest. */}
      <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2">
        <span className="font-mono text-xs font-bold uppercase tracking-wider text-foreground/60">
          Filings
        </span>{" "}
        {BUCKET_MIX.map((mix, i) => (
          <span key={mix} className="inline-flex items-center gap-1.5">
            <span
              aria-hidden="true"
              className="inline-block h-3.5 w-3.5 border border-border"
              style={{ background: `color-mix(in srgb, var(--primary) ${mix}%, var(--card))` }}
            />
            <span className="text-xs text-foreground/60">
              {i === 0 ? "fewest" : i === BUCKET_MIX.length - 1 ? "most" : ""}
            </span>
          </span>
        ))}
      </div>

      {/* The reading panel: preview follows the pointer, a click pins. */}
      <div
        aria-live="polite"
        className="mt-6 border-2 border-border bg-card p-5 shadow-hard-sm sm:p-6"
      >
        {active && activeName ? (
          <div>
            <div className="flex flex-wrap items-baseline justify-between gap-2">
              <h3 className="font-heading text-xl font-black">{activeName}</h3>{" "}
              <p className="font-mono text-xs font-bold uppercase tracking-wider text-foreground/50">
                {pinned === activeAbbr ? "Pinned — tap another state to move" : "Tap to pin"}
              </p>
            </div>
            <dl className="mt-4 grid [&>*]:min-w-0 grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">
              {[
                { k: "Filings", v: fmtInt(active.total) },
                { k: "Certified", v: fmtInt(active.certified) },
                { k: "Denied", v: fmtInt(active.denied) },
                { k: "Approval rate", v: certRate(active) },
                {
                  k: "Median days",
                  v: active.medianDays == null ? "—" : fmtInt(Math.round(active.medianDays)),
                },
                { k: "Median wage", v: fmtWage(active.medianAnnualWage) },
              ].map((d) => (
                <div key={d.k}>
                  <dt className="font-mono text-xs font-bold uppercase tracking-wider text-foreground/50">
                    {d.k}
                  </dt>{" "}
                  <dd className="mt-1 font-heading text-lg font-black tabular-nums">{d.v}</dd>
                </div>
              ))}
            </dl>
          </div>
        ) : (
          <div>
            <h3 className="font-heading text-xl font-black">The whole country</h3>{" "}
            <p className="mt-2 text-base leading-relaxed text-foreground/70">
              {fmtInt(national.total)} PERM filings across {states.length} states and
              territories in the current disclosure window, {fmtInt(national.certified)}{" "}
              certified. Hover or tap a state for its own numbers.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
