"use client";

import { useState, useRef, useMemo, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  ClipboardList,
  Copy,
  Check,
  Pencil,
  Save,
  X,
  RotateCcw,
  Clock,
  CheckCircle2,
  XCircle,
} from "lucide-react";
import {
  generateRecruitmentResultsText,
  calculateRecruitmentStatus,
  formatFilingWindowRange,
  type RecruitmentStatusType,
} from "@/lib/recruitment";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { toast } from "@/lib/toast";
import { handleOperationError } from "@/lib/errors";
import { fmtISODate, fmtISOShort } from "./case-detail-utils";
import type { CaseDetailData } from "./case-detail-types";

// ============================================================================
// TYPES
// ============================================================================

interface RecruitmentResultsCardProps {
  caseData: CaseDetailData;
  onSaveCustomText: (text: string | null) => Promise<void>;
}

// ============================================================================
// STATUS CONFIG
// ============================================================================

const STATUS_CONFIG: Record<
  RecruitmentStatusType,
  {
    icon: typeof Clock;
    bg: string;
    border: string;
    text: string;
    iconCls: string;
    label: string;
  }
> = {
  waiting: {
    icon: Clock,
    bg: "bg-yellow-50 dark:bg-yellow-900/30",
    border: "border-yellow-500",
    text: "text-yellow-900 dark:text-yellow-100",
    iconCls: "text-yellow-600 dark:text-yellow-400",
    label: "WAITING",
  },
  ready: {
    icon: CheckCircle2,
    bg: "bg-green-50 dark:bg-green-900/30",
    border: "border-green-500",
    text: "text-green-900 dark:text-green-100",
    iconCls: "text-green-600 dark:text-green-400",
    label: "READY TO FILE",
  },
  incomplete: {
    icon: Clock,
    bg: "bg-muted",
    border: "border-muted-foreground/30",
    text: "text-muted-foreground",
    iconCls: "text-muted-foreground",
    label: "INCOMPLETE",
  },
  expired: {
    icon: XCircle,
    bg: "bg-red-50 dark:bg-red-900/30",
    border: "border-red-500",
    text: "text-red-900 dark:text-red-100",
    iconCls: "text-red-600 dark:text-red-400",
    label: "EXPIRED",
  },
};

// ============================================================================
// COMPONENT
// ============================================================================

export function RecruitmentResultsCard({
  caseData,
  onSaveCustomText,
}: RecruitmentResultsCardProps) {
  // State
  const [isEditing, setIsEditing] = useState(false);
  const [editValue, setEditValue] = useState("");
  const [isSaving, setIsSaving] = useState(false);
  const [isCopied, setIsCopied] = useState(false);
  const [showRevertDialog, setShowRevertDialog] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Computed
  const status = useMemo(
    () => calculateRecruitmentStatus(caseData),
    [caseData]
  );

  const autoGeneratedText = useMemo(
    () =>
      generateRecruitmentResultsText({
        employerName: caseData.employerName,
        noticeOfFilingStartDate: caseData.noticeOfFilingStartDate,
        noticeOfFilingEndDate: caseData.noticeOfFilingEndDate,
        jobOrderStartDate: caseData.jobOrderStartDate,
        jobOrderEndDate: caseData.jobOrderEndDate,
        jobOrderState: caseData.jobOrderState,
        sundayAdFirstDate: caseData.sundayAdFirstDate,
        sundayAdSecondDate: caseData.sundayAdSecondDate,
        sundayAdNewspaper: caseData.sundayAdNewspaper,
        additionalRecruitmentMethods: caseData.additionalRecruitmentMethods,
        additionalRecruitmentStartDate: caseData.additionalRecruitmentStartDate,
        additionalRecruitmentEndDate: caseData.additionalRecruitmentEndDate,
        isProfessionalOccupation: caseData.isProfessionalOccupation,
        recruitmentApplicantsCount: caseData.recruitmentApplicantsCount,
        recruitmentNotes: caseData.recruitmentNotes,
      }),
    [caseData]
  );

  const displayText = caseData.recruitmentSummaryCustom || autoGeneratedText;
  const isCustom = !!caseData.recruitmentSummaryCustom;

  const config = STATUS_CONFIG[status.status];
  const StatusIcon = config.icon;

  // Handlers
  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(displayText);
      setIsCopied(true);
      toast.success("Copied to clipboard");
      setTimeout(() => setIsCopied(false), 2000);
    } catch (err) {
      handleOperationError(err, {
        userMessage: "Failed to copy text to clipboard.",
      });
    }
  }, [displayText]);

  const handleEdit = useCallback(() => {
    setEditValue(displayText);
    setIsEditing(true);
    setTimeout(() => {
      textareaRef.current?.focus();
      textareaRef.current?.select();
    }, 50);
  }, [displayText]);

  const handleSave = useCallback(async () => {
    setIsSaving(true);
    try {
      const trimmed = editValue.trim();
      // If edited text matches auto-generated, clear custom
      const value = trimmed === autoGeneratedText.trim() ? null : trimmed;
      await onSaveCustomText(value);
      setIsEditing(false);
    } catch (error) {
      handleOperationError(error, {
        userMessage: "Failed to save recruitment summary.",
      });
    } finally {
      setIsSaving(false);
    }
  }, [editValue, autoGeneratedText, onSaveCustomText]);

  const handleCancel = useCallback(() => {
    setIsEditing(false);
    setEditValue("");
  }, []);

  const confirmRevert = useCallback(async () => {
    setShowRevertDialog(false);
    setIsSaving(true);
    try {
      await onSaveCustomText(null);
      setIsEditing(false);
    } catch (error) {
      handleOperationError(error, {
        userMessage: "Failed to revert recruitment summary.",
      });
    } finally {
      setIsSaving(false);
    }
  }, [onSaveCustomText]);

  // Auto-resize textarea
  useEffect(() => {
    if (isEditing && textareaRef.current) {
      const ta = textareaRef.current;
      ta.style.height = "auto";
      ta.style.height = `${ta.scrollHeight}px`;
    }
  }, [isEditing, editValue]);

  // Mandatory steps summary
  const mandatoryDone = [
    status.mandatorySteps.noticeOfFiling.complete,
    status.mandatorySteps.jobOrder.complete,
    status.mandatorySteps.sundayAdFirst.complete,
    status.mandatorySteps.sundayAdSecond.complete,
  ].filter(Boolean).length;

  return (
    <>
      <div className="detail-card">
        {/* ── Header ── */}
        <div className="detail-card-head ch-rec">
          <span className="flex items-center gap-1.5">
            <ClipboardList className="h-3.5 w-3.5" />
            Recruitment Results
            {isCustom && !isEditing && (
              <span className="inline-flex items-center rounded-md bg-blue-50 dark:bg-blue-900 px-1.5 py-0.5 text-[10px] font-medium text-blue-700 dark:text-blue-300 ring-1 ring-inset ring-blue-600/20 ml-1">
                Custom
              </span>
            )}
          </span>
          <div className="flex items-center gap-1">
            {isEditing ? (
              <>
                <button
                  type="button"
                  onClick={handleCancel}
                  disabled={isSaving}
                  className="icon-btn"
                  title="Cancel editing"
                >
                  <X className="h-3.5 w-3.5" />
                </button>
                {isCustom && (
                  <button
                    type="button"
                    onClick={() => setShowRevertDialog(true)}
                    disabled={isSaving}
                    className="icon-btn"
                    title="Revert to auto-generated"
                  >
                    <RotateCcw className="h-3.5 w-3.5" />
                  </button>
                )}
                <button
                  type="button"
                  onClick={handleSave}
                  disabled={isSaving || !editValue.trim()}
                  className="icon-btn"
                  title="Save"
                >
                  <Save className="h-3.5 w-3.5" />
                </button>
              </>
            ) : (
              <>
                <button
                  type="button"
                  onClick={handleCopy}
                  className="icon-btn"
                  title={isCopied ? "Copied!" : "Copy to clipboard"}
                >
                  <AnimatePresence mode="wait">
                    {isCopied ? (
                      <motion.span
                        key="check"
                        initial={{ scale: 0.5, opacity: 0 }}
                        animate={{ scale: 1, opacity: 1 }}
                        exit={{ scale: 0.5, opacity: 0 }}
                        transition={{ duration: 0.15 }}
                      >
                        <Check className="h-3.5 w-3.5 text-green-600" />
                      </motion.span>
                    ) : (
                      <motion.span
                        key="copy"
                        initial={{ scale: 0.5, opacity: 0 }}
                        animate={{ scale: 1, opacity: 1 }}
                        exit={{ scale: 0.5, opacity: 0 }}
                        transition={{ duration: 0.15 }}
                      >
                        <Copy className="h-3.5 w-3.5" />
                      </motion.span>
                    )}
                  </AnimatePresence>
                </button>
                <button
                  type="button"
                  onClick={handleEdit}
                  className="icon-btn"
                  title="Edit recruitment summary"
                >
                  <Pencil className="h-3.5 w-3.5" />
                </button>
              </>
            )}
          </div>
        </div>

        {/* ── Filing Window Status Banner ── */}
        {status.status !== "incomplete" && (
          <div
            className={cn(
              "border-b-[3px] border-border p-4",
              config.bg
            )}
          >
            <div className="flex items-center gap-3 mb-1">
              <StatusIcon
                className={cn("h-4 w-4 shrink-0", config.iconCls)}
              />
              <span
                className={cn(
                  "font-mono text-[0.68rem] font-bold uppercase tracking-wide",
                  config.text
                )}
              >
                {config.label}
              </span>
            </div>
            <p className={cn("text-sm font-medium ml-7", config.text)}>
              {status.message}
            </p>
            {status.filingWindowOpens && status.filingWindowCloses && (
              <div className={cn("mt-2 ml-7 space-y-0.5", config.text)}>
                <p className="text-xs opacity-80">
                  Filing window:{" "}
                  <span className="font-medium">
                    {formatFilingWindowRange(
                      status.filingWindowOpens,
                      status.filingWindowCloses
                    )}
                  </span>
                </p>
                {status.status === "waiting" &&
                  status.daysUntilWindowOpens !== undefined && (
                    <p className="text-xs opacity-80">
                      {status.daysUntilWindowOpens} day
                      {status.daysUntilWindowOpens !== 1 ? "s" : ""} until
                      window opens
                    </p>
                  )}
                {status.status === "ready" &&
                  status.daysRemainingInWindow !== undefined && (
                    <p className="text-xs font-semibold">
                      {status.daysRemainingInWindow} day
                      {status.daysRemainingInWindow !== 1 ? "s" : ""} remaining
                    </p>
                  )}
              </div>
            )}
          </div>
        )}

        {/* ── DOL Text ── */}
        <div
          className={cn(
            "border-b-[3px] border-border p-4",
            isCustom && !isEditing && "border-l-4 border-l-blue-500"
          )}
        >
          {isEditing ? (
            <textarea
              ref={textareaRef}
              value={editValue}
              onChange={(e) => setEditValue(e.target.value)}
              className="w-full min-w-0 min-h-[200px] bg-transparent text-sm leading-relaxed resize-none outline-none font-mono"
              placeholder="Enter custom recruitment results text..."
            />
          ) : (
            <pre className="whitespace-pre-wrap text-sm leading-relaxed font-sans">
              {displayText}
            </pre>
          )}
        </div>

        {/* ── Compact Summary ── */}
        <div className="field-grid" style={{ padding: 0 }}>
          <div className="field-cell">
            <div className="fc-label">Mandatory Steps</div>
            <div className="fc-val flex items-center gap-1.5">
              {mandatoryDone === 4 ? (
                <Check className="h-3.5 w-3.5 text-green-600" />
              ) : (
                <Clock className="h-3.5 w-3.5 text-muted-foreground" />
              )}
              {mandatoryDone}/4
            </div>
          </div>
          {status.professionalMethods.required && (
            <div className="field-cell">
              <div className="fc-label">Professional Methods</div>
              <div className="fc-val flex items-center gap-1.5">
                {status.professionalMethods.allComplete ? (
                  <Check className="h-3.5 w-3.5 text-green-600" />
                ) : (
                  <Clock className="h-3.5 w-3.5 text-muted-foreground" />
                )}
                {status.professionalMethods.completedCount}/3
              </div>
            </div>
          )}
          <div className="field-cell">
            <div className="fc-label">Applicants</div>
            <div className="fc-val mono">
              {caseData.recruitmentApplicantsCount || "-"}
            </div>
          </div>
          <div className="field-cell">
            <div className="fc-label">Recruitment Period</div>
            <div className="fc-val mono">
              {status.recruitmentEndDate
                ? `${fmtISOShort(caseData.recruitmentStartDate)} to ${fmtISOShort(status.recruitmentEndDate)}`
                : fmtISODate(caseData.recruitmentStartDate)}
            </div>
          </div>
        </div>
      </div>

      {/* ── Revert Confirmation Dialog ── */}
      <Dialog open={showRevertDialog} onOpenChange={setShowRevertDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Revert to Auto-Generated Text?</DialogTitle>
            <DialogDescription>
              This will discard your custom recruitment results text and replace
              it with the automatically generated version. This action cannot be
              undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setShowRevertDialog(false)}
            >
              Cancel
            </Button>
            <Button variant="destructive" onClick={confirmRevert}>
              Revert
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
