/**
 * First-page captures of the Federal Register documents on /policy-changes,
 * keyed by document number. GENERATED by scripts/render_policy_pdfs.py; the
 * sizes are the WebP files' own pixel dimensions and a test asserts they still
 * are. A document with no entry here renders no figure.
 */
export const POLICY_SHOTS: Record<string, { w: number; h: number }> = {
  "2026-03595": { w: 850, h: 1100 },
  "2026-05683": { w: 850, h: 1100 },
  "2026-05942": { w: 850, h: 1100 },
  "2026-06017": { w: 850, h: 1100 },
  "2026-06694": { w: 850, h: 1100 },
  "2026-09289": { w: 850, h: 1100 },
  "2026-10082": { w: 850, h: 1100 },
  "2026-11285": { w: 850, h: 1100 },
  "2026-12542": { w: 850, h: 1100 },
  "2026-13057": { w: 850, h: 1100 },
  "2026-13392": { w: 850, h: 1100 },
  "2026-14439": { w: 850, h: 1100 },
  "2026-14539": { w: 850, h: 1100 },
  "2026-15190": { w: 850, h: 1100 },
  "2026-15450": { w: 850, h: 1100 },
  "2026-15673": { w: 850, h: 1100 },
  "2026-16231": { w: 850, h: 1100 },
  "2026-16252": { w: 850, h: 1100 },
  "2026-16313": { w: 850, h: 1100 },
  "2026-16982": { w: 850, h: 1100 },
  "2026-17324": { w: 850, h: 1100 },
  "2026-18631": { w: 850, h: 1100 },
};
