import { describe, expect, it } from "vitest";
import { fireEvent, render, screen } from "@testing-library/react";

import { US_MAP_VIEWBOX, US_STATES } from "@/lib/usStatesGeometry";
import { USStateMap, type StateStat } from "../USStateMap";

/**
 * Two subjects here: the committed geometry artifact (generated by
 * scripts/build_us_states_geometry.py — these assertions are what keep a bad
 * regeneration out of the repo) and the map's interaction contract (hover
 * previews, click pins, keyboard works).
 */

describe("usStatesGeometry artifact", () => {
  it("carries all fifty states plus DC", () => {
    expect(US_STATES).toHaveLength(51);
    const abbrs = new Set(US_STATES.map((s) => s.abbr));
    for (const must of ["CA", "TX", "AK", "HI", "DC", "RI"]) {
      expect(abbrs.has(must)).toBe(true);
    }
  });

  it("keeps every shape and label anchor inside the viewBox", () => {
    for (const s of US_STATES) {
      expect(s.d.length).toBeGreaterThan(10);
      expect(s.cx).toBeGreaterThanOrEqual(0);
      expect(s.cx).toBeLessThanOrEqual(US_MAP_VIEWBOX.w);
      expect(s.cy).toBeGreaterThanOrEqual(0);
      expect(s.cy).toBeLessThanOrEqual(US_MAP_VIEWBOX.h);
    }
  });

  it("uses the Albers USA composite frame, not a raw projection", () => {
    // The tuck: AK sits bottom-left, HI beside it — both in the lower third.
    const ak = US_STATES.find((s) => s.abbr === "AK")!;
    const hi = US_STATES.find((s) => s.abbr === "HI")!;
    expect(ak.cy).toBeGreaterThan(US_MAP_VIEWBOX.h * 0.6);
    expect(hi.cy).toBeGreaterThan(US_MAP_VIEWBOX.h * 0.6);
    expect(ak.cx).toBeLessThan(US_MAP_VIEWBOX.w * 0.3);
  });
});

const STATS: StateStat[] = [
  { state: "CA", total: 1000, certified: 900, denied: 50, withdrawn: 50, medianDays: 400, medianAnnualWage: 150000 },
  { state: "TX", total: 500, certified: 450, denied: 25, withdrawn: 25, medianDays: 380, medianAnnualWage: 120000 },
  { state: "NY", total: 250, certified: 200, denied: 25, withdrawn: 25, medianDays: 410, medianAnnualWage: 140000 },
];

describe("USStateMap", () => {
  it("renders every state as a focusable control", () => {
    render(<USStateMap states={STATS} />);
    expect(screen.getAllByRole("button")).toHaveLength(51);
  });

  it("shows the national summary until a state is read", () => {
    render(<USStateMap states={STATS} />);
    expect(screen.getByText("The whole country")).toBeInTheDocument();
    expect(screen.getByText(/1,750 PERM filings/)).toBeInTheDocument();
  });

  it("previews on hover and clears on leave", () => {
    render(<USStateMap states={STATS} />);
    const ca = screen.getByRole("button", { name: /California/ });
    fireEvent.mouseEnter(ca);
    expect(screen.getByRole("heading", { name: "California" })).toBeInTheDocument();
    fireEvent.mouseLeave(ca);
    expect(screen.getByText("The whole country")).toBeInTheDocument();
  });

  it("pins on click so the panel survives the pointer leaving", () => {
    render(<USStateMap states={STATS} />);
    const tx = screen.getByRole("button", { name: /Texas/ });
    fireEvent.mouseEnter(tx);
    fireEvent.click(tx);
    fireEvent.mouseLeave(tx);
    expect(screen.getByRole("heading", { name: "Texas" })).toBeInTheDocument();
    expect(screen.getByText(/Pinned/)).toBeInTheDocument();
  });

  it("pins from the keyboard", () => {
    render(<USStateMap states={STATS} />);
    const ny = screen.getByRole("button", { name: /New York/ });
    fireEvent.keyDown(ny, { key: "Enter" });
    fireEvent.blur(ny);
    expect(screen.getByRole("heading", { name: "New York" })).toBeInTheDocument();
  });

  it("says so when a state has no data", () => {
    render(<USStateMap states={STATS} />);
    expect(screen.getByRole("button", { name: /Wyoming: no data/ })).toBeInTheDocument();
  });
});
