#!/usr/bin/env node
/**
 * What to ask Google to recrawl after a change: the public pages a range of
 * commits touched, in the order the Search Console queue
 * (../.planning/gsc-index-priority.md) works them.
 *
 * Search Console takes about 11 indexing requests a day, so the queue spends
 * them where a stale copy costs most: a page that is new, then a page whose
 * own words changed, then one or two of the busiest pages of a changed family
 * (Google reaches the rest of a family through the sitemap, whose lastmod
 * moves on the same rule: scripts/lib_page_inputs.mjs decides for both what
 * a page renders from).
 *
 * The range starts, by default, at the last commit that touched the queue,
 * and ends at the working tree, so a run before or after the deploy's commit
 * gives the same list. Paste the output into the queue as a new
 * "Queue after the <date> deploy" section; the automatic round works the
 * newest section top down.
 *
 *   node scripts/gsc_queue.mjs                 # since the queue's last update
 *   node scripts/gsc_queue.mjs --since 043d1653
 */
import { readFileSync } from "node:fs";
import path from "node:path";

import { git, inputsOf, pageFiles, routeOf } from "./lib_page_inputs.mjs";

const LEDGER = "../.planning/gsc-index-priority.md";
const PUBLIC = `src${path.sep}app${path.sep}(site)${path.sep}(public)${path.sep}`;
const KNOWN = new Set(JSON.parse(readFileSync("scripts/known-routes.json", "utf8")));
// Article families render from content/<type>/<slug>.mdx, which no import reaches.
const CONTENT = /^content\/(blog|guides|changelog)\/([^/]+)\.mdx$/;

/** A real page of each family to request first; Google finds the rest through the sitemap. */
const SAMPLE = {
  "/perm-wages/[slug]": ["/perm-wages/software-developers"],
  "/perm-cities/[slug]": ["/perm-cities/new-york-ny"],
  "/perm-employers/[slug]": ["/perm-employers/google-llc"],
  "/perm-attorneys/[slug]": ["/perm-attorneys/fragomen-del-rey-bernsen-loewy-llp"],
  "/visa-bulletin/categories/[line]": ["/visa-bulletin/categories/eb2-india", "/visa-bulletin/categories/eb3-india"],
  "/perm-industries/[slug]": ["/perm-industries/541511"],
  "/perm-countries/[slug]": ["/perm-countries/india"],
};

function arg(name) {
  const i = process.argv.indexOf(name);
  return i > 0 ? process.argv[i + 1] : null;
}

const since = arg("--since") || git(["log", "-1", "--format=%h", "--", LEDGER]).trim();
if (!since) {
  console.error("no --since and no commit has touched the queue");
  process.exit(2);
}
const sinceDay = git(["log", "-1", "--format=%cs", since]).trim();
const diff = (filter) =>
  git(["diff", "--name-only", "--relative", `--diff-filter=${filter}`, since, "--", "src", "content"])
    .split("\n")
    .filter(Boolean);
// Untracked files are new too: a run before the commit should list them.
const untracked = git(["ls-files", "--others", "--exclude-standard", "--", "src", "content"]).split("\n").filter(Boolean);
const changed = new Set([...diff("ACMR"), ...untracked]);
const added = new Set([...diff("A"), ...untracked]);

// A file that feeds many pages is site-wide polish (a source line that now
// wraps feeds about 60), not news about each page: the sitemap's lastmod
// carries it, and the queue's ~11 requests a day go to pages that changed
// their own words.
const SHARED_MIN = 15;
const pages = pageFiles().filter((f) => f.startsWith(PUBLIC)).map((f) => ({ file: f, route: routeOf(f), inputs: inputsOf(f) }));
const reach = new Map();
for (const pg of pages) for (const f of pg.inputs) reach.set(f, (reach.get(f) ?? 0) + 1);
const shared = [...changed].filter((f) => (reach.get(f) ?? 0) > SHARED_MIN);

const fresh = [];
const edited = [];
const families = [];
for (const { file, route, inputs } of pages) {
  const isNew = added.has(file);
  const touched = isNew || inputs.some((f) => changed.has(f) && (reach.get(f) ?? 0) <= SHARED_MIN);
  if (!touched) continue;
  if (route.includes("[")) families.push(route);
  else if (route !== "/" && !KNOWN.has(route)) console.error(`note: ${route} changed but isn't in scripts/known-routes.json (not public, or not registered)`);
  else (isNew ? fresh : edited).push(route);
}
for (const file of changed) {
  const m = CONTENT.exec(file);
  if (!m) continue;
  const route = `/${m[1]}/${m[2]}`;
  if (!KNOWN.has(route)) continue;
  (added.has(file) ? fresh : edited).push(route);
}

// Shallow pages first: hubs and tools carry more searches than the pages under them.
const order = (a, b) => a.split("/").length - b.split("/").length || a.localeCompare(b);
const uniq = (xs) => [...new Set(xs)].sort(order);
let n = 0;
const out = [`Generated by \`node scripts/gsc_queue.mjs --since ${since}\` (changes since ${sinceDay}).`, ""];
if (fresh.length) {
  out.push("New pages (request):");
  for (const r of uniq(fresh)) out.push(`${++n}. \`${r}\``);
  out.push("");
}
if (edited.length) {
  out.push(`Changed pages (inspect; request any last crawled before ${sinceDay}):`);
  for (const r of uniq(edited)) out.push(`${++n}. \`${r}\``);
  out.push("");
}
if (families.length) {
  out.push("Changed page families (request the sample; the sitemap's lastmod carries the rest):");
  for (const f of uniq(families)) {
    const s = SAMPLE[f];
    out.push(s ? `${++n}. \`${f}\`: ${s.map((x) => `\`${x}\``).join(", ")}` : `- \`${f}\` (no sample set; the sitemap carries it)`);
  }
  out.push("");
}
if (shared.length) {
  out.push(`Site-wide changes, left to the sitemap's lastmod: ${shared.map((f) => `\`${path.basename(f)}\` (${reach.get(f)} pages)`).join(", ")}.`);
  out.push("");
}
if (!n) out.push("No public page changed its own content: nothing to request.");
console.log(out.join("\n"));
