#!/usr/bin/env python3
"""The first page of every Federal Register document on /policy-changes, as printed.

    python3 scripts/render_policy_pdfs.py            # every document without a capture
    python3 scripts/render_policy_pdfs.py --all      # re-render the lot
    python3 scripts/render_policy_pdfs.py --dry-run  # list, download nothing

WHY A PDF PAGE AND NOT A SCREENSHOT. federalregister.gov answers a headless
browser with a CAPTCHA interstitial ("programmatic access ... is limited to
our developer APIs"), measured 2026-09-16: 21 captures, 21 identical files.
That is policy, not a rate limit, and it is not defeated here. govinfo.gov
serves the same document's PDF to a plain request, and the first page as
the Register printed it is a truer picture of a rule than a website's chrome.

WHAT IT WRITES. `public/images/policy/<document_number>.webp` (page 1 at
100 dpi, sixteen grays, lossless, ~850 x 1100) and `src/lib/policyShots.ts`, the typed manifest the
page reads so every <img> declares the file's real pixel size. A document
without a capture renders no figure; run this when the feed gains a
document (the daily ingest logs which ones lack one).
"""
from __future__ import annotations

import argparse
import io
import os
import pathlib
import sys
import time
import urllib.request

import fitz  # PyMuPDF
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib_turso import Turso  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "images" / "policy"
MANIFEST = ROOT / "src" / "lib" / "policyShots.ts"
UA = "permtracker.app policy feed (support@permtracker.app)"
# 100 dpi is legible at the 640px the figure renders at and half the bytes of 110.
DPI = 100
GRAYS = 16


def log(msg: str) -> None:
    print(msg, flush=True)


def documents(db: Turso) -> list[tuple[str, str]]:
    res = db.execute(
        "SELECT document_number, pdf_url FROM policy_notices "
        "WHERE type != 'OFLC announcement' AND pdf_url IS NOT NULL AND correction_of IS NULL "
        "ORDER BY publication_date DESC"
    )
    out = []
    for r in res["response"]["result"]["rows"]:
        vals = [None if c["type"] == "null" else c["value"] for c in r]
        out.append((vals[0], vals[1]))
    return out


def fetch(url: str, retries: int = 3) -> bytes:
    last: Exception | None = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=60) as r:
                data = r.read()
            if not data.startswith(b"%PDF"):
                raise RuntimeError(f"not a PDF ({data[:40]!r})")
            return data
        except Exception as e:  # noqa: BLE001
            last = e
            time.sleep(2 * (attempt + 1))
    raise RuntimeError(f"could not fetch {url}: {last}")


def render(pdf: bytes) -> Image.Image:
    doc = fitz.open(stream=pdf, filetype="pdf")
    pix = doc[0].get_pixmap(dpi=DPI)
    # Grayscale: the Register prints black on white, and a colour encode of
    # that is paying for noise. Measured 2026-09-16: 225 KB RGB at 110 dpi.
    return Image.open(io.BytesIO(pix.tobytes("png"))).convert("L")


def write_manifest() -> int:
    rows = []
    for p in sorted(OUT.glob("*.webp")):
        w, h = Image.open(p).size
        rows.append((p.stem, w, h))
    lines = [
        "/**",
        " * First-page captures of the Federal Register documents on /policy-changes,",
        " * keyed by document number. GENERATED by scripts/render_policy_pdfs.py; the",
        " * sizes are the WebP files' own pixel dimensions and a test asserts they still",
        " * are. A document with no entry here renders no figure.",
        " */",
        "export const POLICY_SHOTS: Record<string, { w: number; h: number }> = {",
    ] + [f'  "{n}": {{ w: {w}, h: {h} }},' for n, w, h in rows] + ["};", ""]
    MANIFEST.write_text("\n".join(lines))
    return len(rows)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--all", action="store_true", help="re-render documents that already have a capture")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    docs = documents(Turso())
    todo = [(n, u) for n, u in docs if args.all or not (OUT / f"{n}.webp").exists()]
    log(f"{len(docs)} documents with a PDF; {len(todo)} to render")
    if args.dry_run:
        for n, u in todo:
            log(f"  {n}  {u}")
        return 0
    failed = 0
    for n, u in todo:
        try:
            im = render(fetch(u))
            path = OUT / f"{n}.webp"
            # Sixteen grays, lossless: 86 KB against 177 KB for lossy q82 on the
            # same page (measured 2026-09-16), and the type stays sharp. A lossy
            # encode spends its bytes on the edges of letters.
            im.quantize(colors=GRAYS).save(path, "WEBP", lossless=True, quality=100, method=6)
            log(f"  ok   {n}  {im.width}x{im.height}  {path.stat().st_size // 1024} KB")
        except Exception as e:  # noqa: BLE001
            failed += 1
            log(f"  FAIL {n}  {str(e)[:120]}")
        time.sleep(0.5)
    held = write_manifest()
    log(f"manifest: {held} captures -> {MANIFEST.relative_to(ROOT)}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
